### ISSUE TITLE
Change api dependencies to implementation dependencies

### ISSUE THREAD

**Issue by vtuan10** [MiSikora/Hyperion-Host-Interceptor#1]
Currently, okhttp and hyperion core are added as `api` dependencies. 
This means, the dependencies are added to the app as well, which implements this library. This causes clashes when i.e. a old version of okhttp is used in the app.
Please change it to `implementation`

**Comment by MiSikora** [comment]
I definitely won't make `OkHttp` an `implementation` dependency as it is part of the public API of this library. Also `OkHttp 4.x` is binary compatible with `OkHttp 3.x` so there must be something additional that fails your builds. If you are using some older version of `OkHttp` then there is nothing I can do. You can fork the library or just copy the few classes that are in it. What are the error message and the stack trace?

As for the `hyperion-core` it is not added to the library at all.

**Comment by vtuan10** [comment]
Thanks for the clarification!
There were mainly errors of vals instead of functions. 
We took this as opportunity as well to update to the newest okhttp library. 
This works then as expected.
